// Pulls the brand kit into the app. Run after updating brand/: `npm run sync:brand`.
//  - Extracts the icon paths and the inline art (illustrations, hero panorama, sprig)
//    from brand/reference/bundle.js into components/wfb/art.generated.ts.
//  - Copies the approved logo files, untouched, into public/brand/logos.
import { copyFileSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const bundle = readFileSync(join(root, "brand/reference/bundle.js"), "utf8");

function extract(name) {
  const m = bundle.match(new RegExp(`var ${name} = (\\{[\\s\\S]*?\\});\\n`));
  if (!m) throw new Error(`Couldn't find ${name} in bundle.js`);
  return JSON.parse(m[1]);
}

const icons = extract("ICONS");
const art = extract("ART");
const keep = Object.fromEntries(
  Object.entries(art).filter(([k]) => k === "panorama" || k === "sprig" || k.startsWith("illo-")),
);

writeFileSync(
  join(root, "components/wfb/art.generated.ts"),
  `// Generated by scripts/sync-brand.mjs from brand/reference/bundle.js. Don't edit by hand.
// "__U__" in the art is replaced with a per-instance id so SVG ids never collide.

export const ICONS = ${JSON.stringify(icons, null, 2)} as const;

export const ART: Record<string, string> = ${JSON.stringify(keep, null, 2)};
`,
);

const logosOut = join(root, "public/brand/logos");
mkdirSync(logosOut, { recursive: true });
for (const f of readdirSync(join(root, "brand/assets/logos"))) {
  if (f.endsWith(".svg")) copyFileSync(join(root, "brand/assets/logos", f), join(logosOut, f));
}
copyFileSync(join(root, "brand/assets/logos/icon.svg"), join(root, "app/icon.svg"));

console.log(`Synced ${Object.keys(icons).length} icons, ${Object.keys(keep).length} art pieces and the logos.`);
